/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as DiagnosisIdRouteImport } from './routes/diagnosis.$id'
import { Route as HireBidIdRouteImport } from './routes/hire.$bidId'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as ProsIdRouteImport } from './routes/pros.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisIdRoute = DiagnosisIdRouteImport.update({
  id: '/diagnosis/$id',
  path: '/diagnosis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HireBidIdRoute = HireBidIdRouteImport.update({
  id: '/hire/$bidId',
  path: '/hire/$bidId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsIdRoute = ProsIdRouteImport.update({
  id: '/pros/$id',
  path: '/pros/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bids': typeof BidsRoute
  '/blueprint': typeof BlueprintRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/wallet': typeof WalletRoute
  '/diagnosis/$id': typeof DiagnosisIdRoute
  '/hire/$bidId': typeof HireBidIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/pros/$id': typeof ProsIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bids': typeof BidsRoute
  '/blueprint': typeof BlueprintRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/wallet': typeof WalletRoute
  '/diagnosis/$id': typeof DiagnosisIdRoute
  '/hire/$bidId': typeof HireBidIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/pros/$id': typeof ProsIdRoute
  '/jobs': typeof JobsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bids': typeof BidsRoute
  '/blueprint': typeof BlueprintRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/wallet': typeof WalletRoute
  '/diagnosis/$id': typeof DiagnosisIdRoute
  '/hire/$bidId': typeof HireBidIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/pros/$id': typeof ProsIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bids'
    | '/blueprint'
    | '/home'
    | '/login'
    | '/market'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/scan'
    | '/wallet'
    | '/diagnosis/$id'
    | '/hire/$bidId'
    | '/jobs/$id'
    | '/pros/$id'
    | '/jobs/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bids'
    | '/blueprint'
    | '/home'
    | '/login'
    | '/market'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/scan'
    | '/wallet'
    | '/diagnosis/$id'
    | '/hire/$bidId'
    | '/jobs/$id'
    | '/pros/$id'
    | '/jobs'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bids'
    | '/blueprint'
    | '/home'
    | '/login'
    | '/market'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/scan'
    | '/wallet'
    | '/diagnosis/$id'
    | '/hire/$bidId'
    | '/jobs/$id'
    | '/pros/$id'
    | '/jobs/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BidsRoute: typeof BidsRoute
  BlueprintRoute: typeof BlueprintRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  MessagesRoute: typeof MessagesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ScanRoute: typeof ScanRoute
  WalletRoute: typeof WalletRoute
  DiagnosisIdRoute: typeof DiagnosisIdRoute
  HireBidIdRoute: typeof HireBidIdRoute
  JobsIdRoute: typeof JobsIdRoute
  ProsIdRoute: typeof ProsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/$id': {
      id: '/diagnosis/$id'
      path: '/diagnosis/$id'
      fullPath: '/diagnosis/$id'
      preLoaderRoute: typeof DiagnosisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/$bidId': {
      id: '/hire/$bidId'
      path: '/hire/$bidId'
      fullPath: '/hire/$bidId'
      preLoaderRoute: typeof HireBidIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/$id': {
      id: '/pros/$id'
      path: '/pros/$id'
      fullPath: '/pros/$id'
      preLoaderRoute: typeof ProsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BidsRoute: BidsRoute,
  BlueprintRoute: BlueprintRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  MessagesRoute: MessagesRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ScanRoute: ScanRoute,
  WalletRoute: WalletRoute,
  DiagnosisIdRoute: DiagnosisIdRoute,
  HireBidIdRoute: HireBidIdRoute,
  JobsIdRoute: JobsIdRoute,
  ProsIdRoute: ProsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
